[wokwi]
version = 1
firmware = "build/wokwi_sim.bin"
elf = "build/wokwi_sim.elf"
rfc2217ServerPort = 4000

[[net.forward]]
from = "localhost:8180"
to = "target:80"

[[chip]]
name = "uart"
binary = "build/wokwi-chips/uart.chip.wasm"
