[wokwi]
version = 1
firmware = "../../build/lilygo_t5.bin"
elf = "../../build/lilygo_t5.elf"
rfc2217ServerPort = 4000

[[net.forward]]
from = "localhost:8180"
to = "target:80"

[[chip]]
name = "uart"
binary = "../../build/wokwi/chips/uart.chip.wasm"

[[chip]]
name = "sx1262"
binary = "../../build/wokwi/chips/sx1262.chip.wasm"

[[chip]]
name = "pca9535"
binary = "../../build/wokwi/chips/pca9535.chip.wasm"

[[chip]]
name = "pcf85063"
binary = "../../build/wokwi/chips/pcf85063.chip.wasm"

[[chip]]
name = "bq27220"
binary = "../../build/wokwi/chips/bq27220.chip.wasm"

[[chip]]
name = "bq25896"
binary = "../../build/wokwi/chips/bq25896.chip.wasm"
